server:
  port: 5612

db:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  database: 'db_gazi'
  username: 'root'
  password: 'patrick'
  synchronize: false

aes256ecb:
  secretKey: 'OchoiceAndGaziMembershipMatching'