server:
  port: 5612

db:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  database: 'db_gazi'
  username: 'root'
  password: 'patrick'
  synchronize: false

jwt:
  secret: 'Secret1234'
  expiresIn: 60*60